[package]
name = "umkc-scheduler"
version = "0.1.0"
authors = ["Samuel Lim <sclg9w@mail.umkc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
