name: Rust

on:
  pull_request:
    branches:
      - nightly
      - master
    

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
