name: Rust

on:
  push:
    branches: [ master, nightly ]
  pull_request:
    branches: [ master, nightly ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd umscheduler
        cargo build --verbose
    - name: Run tests
      run: |
        cd umscheduler
        cargo test --verbose
